version: '3.7'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: allztech-web
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8081:8081
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
      - XDEBUG_CONFIG="remote_host=host.docker.internal remote_port=9001 remote_enable=1"
      - COMPOSER_MEMORY_LIMIT=-1